version: '3'

services:
  
  jenkins:
    image: jenkins
    restart: always
    ports:
      - 8090:8080
      - 50000:50000
    container_name: jenkins
    volumes:
      - ./jenkins_home:/var/jenkins_home/
      - /var/run/docker.sock:/var/run/docker.sock
      - ~/.ssh:/var/lib/jenkins/.ssh
